name: Deploy Packages
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - library/**/package.json

jobs:
    deploy_package:
        name: Publish Package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  run_install: true
                  version: ${{ vars.PNPM_VERSION }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: pnpm

            - name: Setup Configuration
              run: |
                  pnpm config set 'always-auth' "true"

            - name: Deploy to NPM Packages
              run: |
                  pnpm config set '//registry.npmjs.org/:_authToken' "${AUTH_TOKEN}"
                  pnpm --filter=@cmru-comsci-66/* publish -r --access=public --registry=https://registry.npmjs.org/
                  pnpm config delete '//registry.npmjs.org/:_authToken'
              env:
                  AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
