name: Detect and Tag New Version
on: [workflow_dispatch, pull_request, push]

jobs:
    tag-new-versions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - uses: salsify/action-detect-and-tag-new-version@v2
              with:
                  create-tag: true
                  tag-annotation-template: ""
