name: Detect and Tag New Version
on: [workflow_dispatch, push]

jobs:
    tag-new-versions:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'github-actions[bot]' }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - uses: salsify/action-detect-and-tag-new-version@v1.0.3
              with:
                  create-tag: true
