name: Publish
on:
    workflow_dispatch:
        inputs:
            notest:
                description: "Skip (Test & Fix Problems)"
                required: false
                default: false
                type: boolean
            nobumpversion:
                description: "Skip (Bump version)"
                required: false
                default: false
                type: boolean
            bumpversion:
                type: choice
                description: "Bump version"
                required: true
                options:
                    - patch
                    - minor
                    - major
            deploy_web:
                description: "Deploy WebSite"
                required: false
                default: true
                type: boolean
            includes_web:
                description: "Includes WebSite"
                required: false
                default: false
                type: boolean
            includes_package:
                description: "Includes Packages"
                required: false
                default: false
                type: boolean

jobs:
    test:
        name: Test & Fix Problems!
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs.notest == 'false' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  run_install: false
                  version: ${{ vars.PNPM_VERSION }}

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: pnpm

            - name: Install Dependencies
              run: pnpm install

            - name: Run ESLint
              run: pnpm run fix

            - name: Automatically Commit Changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "chore(eslint): fix problems"
                  skip_checkout: true

    bumpversion:
        name: Bump Version
        needs: [test]
        runs-on: ubuntu-latest
        outputs:
            outversion: ${{ steps.package.outputs.version }}
        if: |
            always() && github.event.inputs.nobumpversion == 'false' &&
            !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  run_install: |
                      - recursive: true
                        args: [--frozen-lockfile, --strict-peer-dependencies, --ignore-scripts]
                      - args: [--global, '@jsdevtools/version-bump-prompt']

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: pnpm

            - name: Bump Version
              id: bumpversion
              run: pnpm bump ${{ github.event.inputs.bumpversion }}

            - name: Bump Version (Packages)
              if: |
                  always() && github.event.inputs.includes_package == 'true' &&
                  !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
              run: pnpm --filter=./library/** ci:bump ${{ github.event.inputs.bumpversion }}

            - name: Bump Version (WebSite)
              if: |
                  always() && github.event.inputs.includes_web == 'true' &&
                  !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
              run: pnpm --filter=./client ci:bump ${{ github.event.inputs.bumpversion }}

            - name: Get Version
              id: package
              if: steps.bumpversion.outcome == 'success'
              uses: Saionaro/extract-package-version@v1.2.1

            - name: Automatically Commit Changed
              if: steps.package.outcome == 'success'
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  tagging_message: "v${{ steps.package.outputs.version }}"
                  commit_message: "chore(release): publish v${{ steps.package.outputs.version }}"
                  skip_checkout: true

    deploy_website:
        name: Publish WebSite
        needs: [bumpversion]
        runs-on: ubuntu-latest
        if: |
            always() && github.event.inputs.deploy_web == 'true' &&
            !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}

            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-args: "--prod"
                  vercel-org-id: ${{ secrets.ORG_ID }}
                  vercel-project-id: ${{ secrets.PROJECT_ID }}
